### ISSUE TITLE
Text & media + background banners

### ISSUE THREAD

**Issue by pikemurdy** [utkwdn/utkwds#124]
For 1.2
- [ ] Remove auto caption insert on ALL photos
- [ ] when caption shows, caption font should be smaller than body text
- [ ] Element breaks in editor when removing paragraph. The width changes based on how much text and size of photo. See screenshots 3 and 4 - https://docs.google.com/document/d/1Lk-HytSDMJ-FkEG8iSRQv-MZXn4OwsNcR6dRxmalhEA/edit
- [ ] Figma mockup shows it attached to right side of window, it curently has right margins – was this on purpose?

**Comment by spworky** [comment]
@pikemurdy are there any changes we need to look at for this one for 1.1? Doesn't look like it.

**Comment by lshoe** [comment]
- The paragraph issue appears to be fixed. 
- The caption size issue does not appear to be fixed.
- Something weird—when the caption does appear for a photo, and that photo is replaced with another image that does NOT have a caption, the caption of the initial photo remains. I've encountered this with other patterns that have images.

**Comment by pikemurdy** [comment]
The 'auto caption' issue is core wordpress functionality, and would be a great deal of work to remove, so let's leave it.
