### ISSUE TITLE
[Media Text & Banners] 

### ISSUE THREAD

**Issue by pikemurdy** [utkwdn/utkwds#125]
- Need placeholder text beneath headline (paragraph is there just empty)
- fancy link needs more padding between edge of screen. Slamming into the side of the box for long links. (on hover the arrow jumps lines)

**Comment by reasterbrooknc** [comment]
- Let's chat about placeholder text within the WDS—WordPress adds guide text within the block editor that makes it somewhat unnecessary to have placeholder text, but we want to be consistent across the system. 
- Fixed padding issue with fancy links.

**Comment by reasterbrooknc** [comment]
Complete.
