### ISSUE TITLE
Image & text banners

### ISSUE THREAD

**Issue by pikemurdy** [utkwdn/utkwds#128]
- [x] Give just a little more breathing room between text and image; need some kind of consistency between icon/image and text in three previous components

For 1.2
- [x] Image should align top
- [x] Turn auto caption off

**Comment by kellieward** [comment]
Does Image + text white have more top and bottom margin than the smokey and light gray components? Is there a reason for this?

**Comment by reasterbrooknc** [comment]
Ready to close @pikemurdy?
