### ISSUE TITLE
Contact card banner

### ISSUE THREAD

**Issue by pikemurdy** [utkwdn/utkwds#129]
Existing feedback for 1.2:
- [x] On mobile, the questions headline is too close to fancy links; needs padding on bottom of fancy links
- [x] Need more space between text and contact card columns
- [x] Instead of "Questions? Here to Help!", we want to switch with "Contact us for help".

**Comment by kellieward** [comment]
Content is almost touching fancy links. Do we need margin bottom? 
<img width="1689" alt="Screen Shot 2023-12-05 at 9 07 51 AM" src="https://github.com/utkwdn/utkwds/assets/40268947/bd32c6ac-38bb-4c25-bd6b-e30ad2f6c1b9">

**Comment by pikemurdy** [comment]
Systematize the margins/spacing.

**Comment by reasterbrooknc** [comment]
Ready for review https://wds-dev.utk.edu/contact-card-banner @pikemurdy
