### ISSUE TITLE
Contact Cards

### ISSUE THREAD

**Issue by pikemurdy** [utkwdn/utkwds#132]
- [x] photo isn’t filling full vertical space
- [x] no visible difference in heading size when change from H2/H3/H4 etc Need to have visual change in size for ADA

Existing feedback for 1.2:
- [ ] can we make it not pull in the caption text automatically for all cards?
- [ ] reduce font size slightly for contact info (everything but the heading)
- [ ] person's title leading needs to be reduced slightly
- [ ] Need top and bottom margins
- [ ] number of characters should be limited for cards at wide/full width. Long titles get strange 
- [ ] image ratio size changes for type of image – so spacing get weird at slimmer cropped

**Comment by kellieward** [comment]
Photo looks better, seems to be filling space. I still couldn't get the font size to change when choosing H2/H3/H4

**Comment by reasterbrooknc** [comment]
@nc-mhenderson please address h2/h3/h4 issue
