### ISSUE TITLE
Horizontal Cards

### ISSUE THREAD

**Issue by pikemurdy** [utkwdn/utkwds#134]
- [x] list links should have more space between items so you can differentiate from multi-line from single element
- [x] no visible difference in heading size when change from H2/H3/H4 etc Need to have visual change in size for ADA
- [x] need padding around paragraph text

For 1.2
- [ ] Remove captions from photo on all variants

**Comment by spworky** [comment]
This still needs work. Don't think all changes are in the place.

- [ ] 2up — Not enough padding around paragraph text. Still very tight to the right hand side of the box with image. 
![horiz-card-2up-image-no-padding-right](https://github.com/utkwdn/utkwds/assets/69162526/a947e31a-6c64-4ea3-a9ab-f575b0046182)

- [ ] 2up —No padding on left hand side of paragraph without image.
![horiz-card-2up-no-image-no-padding-left](https://github.com/utkwdn/utkwds/assets/69162526/376ae20e-e8c5-4f82-aa18-31479a3aecaa)

- [ ] Single card —content chunk is aligning to right side of box. (so when paragraph is short alignment is strange.)
![horiz-card-1up-short content-align-right](https://github.com/utkwdn/utkwds/assets/69162526/ef407cad-0fe6-49c7-8344-4097180cc676)

- [ ] 2up —Header not changing visible size for h3 vs h4.  No visual difference in editor or live.
![horiz-card-2up-h3-vs-h4-not-visible-difference](https://github.com/utkwdn/utkwds/assets/69162526/ccc8ae09-e9df-4aed-af77-b3158076a407)

**Comment by pikemurdy** [comment]
@spworky Can you drop a link to where these are built out?

**Comment by spworky** [comment]
@pikemurdy No problem – https://wds-dev.utk.edu/sp-component-test-02

**Comment by reasterbrooknc** [comment]
@nc-mhenderson please address items from Sandra's comment above 
- h2/h3/h4 issue
- 2up padding issue
- single card spacing issue

**Comment by nc-mhenderson** [comment]
https://github.com/utkwdn/utkwds/pull/212
