### ISSUE TITLE
Image & subject link card

### ISSUE THREAD

**Issue by pikemurdy** [utkwdn/utkwds#135]
- [x] no visible difference in heading size when change from H2/H3/H4 etc Need to have visual change in size for ADA
- [x] Subject 2up white on Smokey—when a link is added to the text, it turns white and thereby becomes invisible.

For 1.2
- [x] Remove auto caption on all variations
- [ ] adding a link is not intuitive
- [ ] formatting on text link sometimes changes when adding a URL to words

**Comment by pikemurdy** [comment]
@reasterbrooknc I'm confused on this one. Which pattern is this referring to?

**Comment by reasterbrooknc** [comment]
It's the subject card! https://wds-dev.utk.edu/test-page-subject-card-patterns

**Comment by pikemurdy** [comment]
Okay. I'm seeing a difference in h2/h3/h4.

**Comment by spworky** [comment]
Heading sizes look correct. 

Wondering if there is an easier way to show that the intended use is to be linked. Should the default text in the pattern be linked to a # to show intended purpose?

**Comment by pikemurdy** [comment]
We can talk about it, but I don' think so for 1.1.

**Comment by lshoe** [comment]
@pikemurdy @reasterbrooknc 

**Uh oh! I found a bug.** Subject 2up white on Smokey—when a link is added to the text, it turns white and thereby becomes invisible.

<img width="1010" alt="image" src="https://github.com/utkwdn/utkwds/assets/7997924/cb88deff-500e-4ad6-97fe-9f3c5e25c014">

**Comment by lshoe** [comment]
Same bug on the 3up white on Smokey pattern.

<img width="1069" alt="image" src="https://github.com/utkwdn/utkwds/assets/7997924/4d1464b2-4ab9-4ee4-8cd1-75adb4d3ecc1">

**Comment by reasterbrooknc** [comment]
@nc-mhenderson please address link text color bug in Leigh's comments above.
