### ISSUE TITLE
Gallery: Large, small + orange pattern

### ISSUE THREAD

**Issue by pikemurdy** [utkwdn/utkwds#138]
- [x] there should not be a spacer above the smaller image inside the column (in the pattern)
- [x] classes are missing on the column container and on the images which is making the alignment incorrect (especially on mobile)
- [x] as it scales, this should still have space between the edges and the browser at medium widths 
- [x] mobile stacked images should overlap the orange bar – the top one should only be slightly over the orange
- [x] image sizing at mobile is not correct—the images should still maintain one is slightly larger and one is smaller
- [x] orange bar should come up higher behind the images.
- [x] image size relationship is not right. smaller image should be 102% larger 
- [x] space between large and small image is slightly too small, needs to increase
- [x] need more white space between this patern and pattern above
- [x] See pre-existing pattern here https://sandbox-dev.utk.edu/gallery/
- [ ] Orange bar disappear sometimes, it happened on my test page; may have been due to being in the same group? Check if this is happening on your end.
- [x] Need to remove auto caption insert on ALL photos

**Comment by reasterbrooknc** [comment]
Checking off items in description, noting that we pulled latest version from Sandbox and teams reviewed together.
