### ISSUE TITLE
Archive and Blog Pages

### ISSUE THREAD

**Issue by pikemurdy** [utkwdn/utkwds#142]
- [x] Implement the agreed upon Figma mockup.

**Comment by pikemurdy** [comment]
Don't have the Figma file, but this looks right to me.

**Comment by kellieward** [comment]
Also cannot find mockup. Is date supposed to be larger than text excerpt? Do we always want tags showing? I'm assuming this is a setting, where tags on archive page can be turned on and off?

**Comment by pikemurdy** [comment]
I think that needs to be a feature, @kellieward . But we may have to put it on the backlog.
