### ISSUE TITLE
[Search Results] visual enhancements

### ISSUE THREAD

**Issue by pikemurdy** [utkwdn/utkwds#144]
- [x] On mobile, the header on the search page does not minimize properly
- [x] header gets tiny on mobile
- [x] Tabs are Tiny on Mobile Search Page https://wds-dev.utk.edu/?s=test
- [x] Font issues on headlines - not rendering correctly https://wds-dev.utk.edu/?s=undergraduate

**Comment by reasterbrooknc** [comment]
Also addressing these:

- [ ] Missing dominant tab size, hover font color should be link hover color, background color of search box is blueish
- [ ] Active state should be slightly larger, font bold

**Comment by reasterbrooknc** [comment]
Complete, on dev.
