### ISSUE TITLE
Create a tab group

### ISSUE THREAD

**Issue by pikemurdy** [utkwdn/utkwds#148]
- [ ] Similar to the accordion, but tabs.

**Comment by reasterbrooknc** [comment]
Needs to match what is on search page and existing UTK site. Also needs to be implemented for tabs on documentation site.

**Comment by reasterbrooknc** [comment]
Noting that these are done and ready for NewCity QA

**Comment by pikemurdy** [comment]
This looks good. I actually built it locally on the latest version of the theme on the development branch. I didn't think it was too hard to use in the editor. Not sure it _needs_ placeholder content? But whatever you think.

However, it's not keyboard navigable, as far as I could tell. When I was tabbing (with the tab key) through, I could not select the inactive tabs. I saw you could use the arrows, but I'm not sure how intuitive that is (I see that it's that way in our search area). But I'd love to know your thoughts, this may have been an oversight on our part. I use the tab key to navigate sites a lot and wouldn't have thought to switch to the arrows. What is the thinking here?

**Comment by nc-mhenderson** [comment]
@pikemurdy When focused on the tab use the arrow keys to select the other tabs. This is best practice as defined by the W3C: https://www.w3.org/WAI/ARIA/apg/patterns/tabs/. This is identical behavior as the search page.

**Comment by pikemurdy** [comment]
This is good.

**Comment by reasterbrooknc** [comment]
Starter content from Rachel D.:

Tab 1
First panel is open or in focus by default when the page loads.

Tab 2
Second panel is hidden until the user selects it. 

Tab 3
Third panel is hidden until the user selects it.

Tab 4
Fourth panel is hidden until the user selects it.
