### ISSUE TITLE
Universal Nav

### ISSUE THREAD

**Issue by pikemurdy** [utkwdn/utkwds#151]
- [ ] The universal nav shouldn't be a menu you have to build, it should be built into the theme. Only the links should be editable, not the words

**Comment by reasterbrooknc** [comment]
We plan to remove the ability to add the utility nav in the menu editor and to add additional fields in the customizer to make the links editable. If present, these custom values will be used. If not, it will use the default links.

**Comment by reasterbrooknc** [comment]
Need to add guidance on how to edit this menu to documentaiton site.

**Comment by reasterbrooknc** [comment]
Ready for review @pikemurdy

**Comment by pikemurdy** [comment]
Looks good.
