### ISSUE TITLE
Role-based permissions set on blocks

### ISSUE THREAD

**Issue by pikemurdy** [utkwdn/utkwds#154]
Editors should not have access to styling switches, only admins.

**Comment by pikemurdy** [comment]
Ugh. Not ideal and pretty disappointing. Do we know when/if it is planned for WP to have permissions functionality?

Also, surely this has come up before. How have you handled it with other clients?

**Comment by reasterbrooknc** [comment]
This is a limitation we face by leveraging core blocks. When building with custom blocks, you have control over these settings from the ground up.

Partially synced patterns are slated for [WP 6.5 in March 2024](https://make.wordpress.org/core/2023/12/07/roadmap-to-6-5/). Plenty to discuss on this, but this could be advantageous for restricting controls and also updating patterns in place.
