### ISSUE TITLE
Two level navigation

### ISSUE THREAD

**Issue by pikemurdy** [utkwdn/utkwds#217]
The menu should not accept (meaning, not show) menus deeper than 1 level.

<img width="281" alt="Screenshot 2023-12-13 at 4 45 50 PM" src="https://github.com/utkwdn/utkwds/assets/7902085/4f5a5f9f-7c56-4a2b-b23d-5a271ac854cf">

**Comment by nc-mhenderson** [comment]
This restriction was added after this menu was created.

Can we ask folks to recreate these menu and/or fix the nesting or are we wanting to force this in code?

**Comment by pikemurdy** [comment]
Not sure what you mean by ”restriction” or "force this in code". I know we'll never be able to get people to occasionally adding a third level of navigation.

In the past, I've used the “depth” attribute in `wp_nav_menu`. But I looked through your code and it looks like y'all are building the menu differently somehow.

`
<?php
  wp_nav_menu( array(
  'container'=> '',
  'items_wrap'=>'%3$s',
  'depth' => 2,
  'theme_location' => 'single-menu',
 ) );
?>
                `

**Comment by nc-mhenderson** [comment]
If you create a menu with the menu builder you can't nest this deep. 

The menu example was created after I added this restriction in the menu builder.

**Comment by pikemurdy** [comment]
Okay. I just tested this, yes. I didn't know you could do that. Can you point me to the file/code that does this?

**Comment by nc-mhenderson** [comment]
Sure thing:
https://github.com/utkwdn/utkwds/blob/9280a181850e1667d7bc3afab676f53f83a993f0/src/inc/functions/inc-menu.php#L23
