### ISSUE TITLE
Remove hyphenation in headlines

### ISSUE THREAD

**Issue by pikemurdy** [utkwdn/utkwds#218]
The hyphenated headlines are quite distracting, especially when multiple headlines are on the screen. Second Mile developed a different solution for the admissions site, we can reach out to them for it if need be.

**Comment by pikemurdy** [comment]
@pikemurdy to ask Sam for the code.

**Comment by pikemurdy** [comment]
SecondMile says the fix is here:

https://github.com/secondmile/utksm/blob/main/src/scss/styles/_typography.scss

**Comment by nc-mhenderson** [comment]
addressed by #246

**Comment by reasterbrooknc** [comment]
Ready for your review @pikemurdy

**Comment by pikemurdy** [comment]
This is good to go.
