### ISSUE TITLE
Media & text with CTA

### ISSUE THREAD

**Issue by pikemurdy** [utkwdn/utkwds#219]
- [ ] The space between the Paragraph and the Fancy Link list on the "Media & text with CTA" patterns is less than it is on the "Media & Text Banner" patterns - see screen shot attached.

![fancy-link-spacing](https://github.com/utkwdn/utkwds/assets/7902085/ded07da2-9620-4e1a-bbad-f05c5506b84a)

**Comment by pikemurdy** [comment]
Figma systemization would fix this.

**Comment by reasterbrooknc** [comment]
Addressed by #129
