### ISSUE TITLE
Name the theme torch

### ISSUE THREAD

**Issue by pikemurdy** [utkwdn/utkwds#222]
Change the name of the theme from "University of Tennessee, Knoxville Design System WordPress Theme" to "Torch WDS". And change the description to "The official University of Tennessee, Knoxville Web Design System theme."

**Comment by nc-mhenderson** [comment]
@pikemurdy Just to clarify, we are keeping the directory name and namespace the same? 

Changing this would require a major code refactor.

**Comment by nc-mhenderson** [comment]
@pikemurdy bumping this.

**Comment by pikemurdy** [comment]
No, don't do anything that would require a major code refactor. I just mean in the stylesheet:

```
/*!
Theme Name: University of Tennessee, Knoxville Design System WordPress Theme
Theme URI: http://www.utk.edu/
Author: The UT Web Team
Author URI: http://communications.utk.edu
Description: The official UT WordPress Design System theme.
Version: 1.1.0
*/
```

to 

```
/*!
Theme Name: Torch WDS
Theme URI: http://www.utk.edu/
Author: The UT Web Team
Author URI: http://communications.utk.edu
Description: The official University of Tennessee, Knoxville Web Design System theme.
Version: 1.1.0
*/
```

That wouldn't cause any issues would it? Nothing I don't know about?

**Comment by reasterbrooknc** [comment]
This is ready for your review @pikemurdy!
