### ISSUE TITLE
Create an "Update Button" to the control panel.

### ISSUE THREAD

**Issue by pikemurdy** [utkwdn/utkwds#224]
is there a way to get an update button in the control panel when the theme is updated.

**Comment by mike-henderson** [comment]
We have update versioning in the release documentation/notes/process doc.

There is a slight bug with the version notes. We can try pointing it to the release notes on Storefront but WP doesn’t like pointing to a github release page.

An issue with the Storefront notes is that it is behind a login so we cant use this until Storefront is public.

**Comment by nc-mhenderson** [comment]
We have update versioning in the release documentation/notes/process doc.

There is a slight bug with the version notes. We can try pointing it to the release notes on Storefront but WP doesn’t like pointing to a github release page.

An issue with the Storefront notes is that it is behind a login so we cant use this until Storefront is public.

**Comment by nc-mhenderson** [comment]
There is a case when the `main` branch is published the theme will point to a zip file included in the release notes page.

There is a workaround by not publishing the `info.json` file until the release page is published but it is nicer to keep all the version bump commits in one place.

**Comment by nc-mhenderson** [comment]
The theme update will not work on local install due to the way the theme directory is linked to the `build` folder in the current development configuration.
