### ISSUE TITLE
Gray and Headline Alignment issue

### ISSUE THREAD

**Issue by pikemurdy** [utkwdn/utkwds#226]
When I add the "Media & text, light gray" pattern as the first thing on a page, the gray background begins showing in the Page Title area - behind the bottom of the H1 text - see screen shot attached.

Please attach any documentation you would like to share with us.

media-and-text-light-gray.jpg <https://u8180940.ct.sendgrid.net/ls/click?upn=1c3RmxFj2B3XKB-2FNDFcL1RZ8dAbrKzrY-2FLJDJhwTIPFJZNUhvBsvIsU4sELJdKsZHEAd9jS6Hc7YYO2xXaW8W2t-2FAJ7Wlou2tTWcSpq09tJ54UXBc7vUZGOXgTxnFbmDqxMdFRJ9Z2AkRNXMx9akJKGSk92bkdf2sNfzV8WCRVOURIxrPLbXKmpGRHfve9ClZ9gXtBS1M9yxYP-2Byavg6DmsKbubxXLWFiQE27sIKXIf2vUsT8aWfc3kZFf2hx-2FWE8fnBsNlwZYuaJLz1P3AvKQ-3D-3DU-g1_GGzKQfLYCKE077qTA-2FDvaG1-2F3nZEA3c2qnNSCC2tNqjYI2IVL2af58O13G2wieTGfWXZo-2BsiFtRXpxUL-2BW9Ra5P-2BvMJnfXP-2FNrhbinY3TTXQoum5sC-2FmTEQBVW25-2B0Tqby1Kl5qw5WRTz1jKlai9-2BJUYeMkmjoBFYb4oLS-2BC5VFmNFnUepHLJjHc-2FUwPlJAiAtuPaI69VPyWTo7aqKCVx6mfo2SNeCRGzDy6FrZF0Q0-3D>

**Comment by reasterbrooknc** [comment]
@pikemurdy A point of clarification here—should this hero component ever display with a page title? If no, then this wouldn't be an issue but the intended usage should be added to the documentation. 

This might also be a design/UX question that we should discuss with the teams.

**Comment by pikemurdy** [comment]
I think we should discuss with the larger team. But I think we need make things as 'bullet proof' as possible. I know it's not possible 100% of the time, but if there's a case where it seems logical to stick a pattern somewhere, it should work okay.

**Comment by pikemurdy** [comment]
This seems to be corrected now. Has the headline area been adjusted recently, @reasterbrooknc ?

**Comment by reasterbrooknc** [comment]
This popped up as we were QAing Points of Pride, and I ended up making a [separate issue](https://github.com/utkwdn/utkwds/issues/346) and testing this behavior for all of the grey background components. Mike wrote a fix and is working on exceptions.
