### ISSUE TITLE
New Hero Area

### ISSUE THREAD

**Issue by pikemurdy** [utkwdn/utkwds#228]
I would like to request a Hero area pattern like the one being used on the Admissions site (see screen shot).

Please attach any documentation you would like to share with us.

admissions-hero-pattern.jpg <https://u8180940.ct.sendgrid.net/ls/click?upn=1c3RmxFj2B3XKB-2FNDFcL1RZ8dAbrKzrY-2FLJDJhwTIPFJZNUhvBsvIsU4sELJdKsZHEAd9jS6Hc7YYO2xXaW8W2t-2FAJ7Wlou2tTWcSpq09tLvUTIKKRWUVy2IYa-2FMLVdh9FhqLzyBtHWtBV54AGEBgFTSkVidSoY8Y9-2FfVSCsmJhCLYyNSec0pQnomzgL3T6ngUJ1msMZS5Qln0wDhOxh2BnlAiSsROvdP81uP-2B7vamkwsycIH-2BK369TAEIX2aIqttDY5ihI1rhFAo3bUEdolIA-3D-3DY6xl_GGzKQfLYCKE077qTA-2FDvaG1-2F3nZEA3c2qnNSCC2tNqjYI2IVL2af58O13G2wieTGYSZPO3HngeE5NS-2FYnbwiGYyByKyDYGxUGle8XVGpl0N-2Fl15zDsZGxoYG0p4iSwoqhVAjWLShOl7VoHq-2Fjb3x8d-2BOQc-2BUSDXjRb3pkNxUKVzmfMFN3UHQiRT-2BKU-2FcLu8aOVJWfYZxSb0lS2yo8TipYNSDEkEj9HjeMsiKr7mq0VU-3D>

**Comment by pikemurdy** [comment]
This should serve as "inspiration". But, I think at many screen sizes,[ it gets odd,](https://admissions.utk.edu) so should not just be copied wholesale.

It should be built from Figma tokens.

Things that are important:
- the 'quiet' headline (H1) above a chunky text (p, maybe?)
- Big image
- The CTA area.

**Comment by reasterbrooknc** [comment]
From 3/27 meeting with Purdy and Anna:
Recommendation: move forward with approved hero, assuming hopefully we can add in the superhead along the way. 
- Leigh and Sandra will come back with recommendations on font in two weeks. Know that it may be Sophia, or may be Montserrat. 
- They like the one with the textured orange bar, but remove the button CTA, and realign the CTA link. General guidance would be to not use a button here.

**Comment by reasterbrooknc** [comment]
### Approved designs (superhead TBD)
[Figma file](https://www.figma.com/file/9wVbrIffcRoNUgnM4ALqWL/UTK-%7C-Design-v05?type=design&node-id=7183%3A2654&mode=design&t=mC0fyMn6aXVk3YIM-1)
[hero  2.zip](https://github.com/utkwdn/utkwds/files/14828049/hero.2.zip)

**Comment by reasterbrooknc** [comment]
- Name: Full-Width Hero
- H1: Optional Superhead. If no Superhead, Heading is H1.
- H2: If superhead, Heading is H2.
- Optional Subhead is styled paragraph block. 
- One [CTA Link](https://github.com/orgs/utkwdn/projects/2/views/1?pane=issue&itemId=58284973) in pattern. 
- Image max height: 700px
- Bottom white box expands downward as paragraph text gets longer.

**Metadata** (for @rdelaude)
- Description:
- Keywords:
- Default Text: 

**Documentation**
- Recommendations on character count and how to use CTA links.
- Include info about anchor point on image.
- Should only be used as hero.
- Category: Hero?
 
TBD: Mike is calling this a SUPER PATTERN. It is aware it is a header, and takes over the page template if it exists. Logic has to be inserted into the templates to recognize this pattern (e.g. La Salle). Parsing functionality, template functionality, block functionality.

**Comment by reasterbrooknc** [comment]
Updates on programmatically controlling the header:
- There is a built in way to restrict a pattern for different page templates. Plan is to restrict the hero to the blank page or page without title. The pattern uses the page title for the h1.
- No current solution to restrict the pattern to one instance—might only be possible if the pattern was a block instead.

For the future:
- Set cover to feature image of current page—documentation on this?
- This pattern could be good use case for page templates.

**Comment by rdelaude** [comment]
@nc-mhenderson 
For the keywords — do these use partial-phrases to search the available components or do they need redundancy built in to return a two-word phrase? e.g.  will "page header" do as a keyword, or do we also need to seed it with "header" in case someone doesn't type "page"? Also assuming case is irrelevant...what about number? (e.g. hero, heroes)

Description: Bold, large-image page header
Keywords: hero, header, head, heading, title, full-width, full width, full bleed
Default Text: 

Optional superheading
H1 page title, very short
Optional subheading
Paragraph 25 words or fewer. Use to orient users or unblock any barriers that would keep them from clicking a CTA link. 
Optional CTA link

**Comment by nc-mhenderson** [comment]
I added "page header" as a keyword and it popped up as soon as I typed “hea”

**Comment by reasterbrooknc** [comment]
Design QA:
- Remove space between bottom of nav/breadcrumbs and top of hero
- Text and white box should extend down, not up, as text gets longer
