### ISSUE TITLE
Icon selector custom block 

### ISSUE THREAD

**Issue by reasterbrooknc** [utkwdn/utkwds#229]
### 5/13 Update
- One icon library (just use two-color icons**) 
- [ut-icons-web-ready.zip](https://github.com/utkwdn/utkwds/files/15298611/ut-icons-web-ready.zip)
- White and light gray background variations
- Use image + text banner design

**Comment by pikemurdy** [comment]
### Style Cues

UT icons should be built with a consistent line weight to unify our family of icons. When developing icons, follow our template guidance below.

### Grid

All UT icons should be based on a foundational grid of 125 x 125 pixels. Whether you are reformatting past icons or creating new icons, scale to this grid to establish consistency in size.
Consistent Stroke Weight

The primary purpose of following a 125 x 125 pixel grid is to establish universal consistency in scale and line weight. We have two line weights used in our icons to emphasize parts of the icons. All line weights should follow the sizes below when using the grid:

- Thicker line - 2.25pt
- Thinner line - 1.5pt
- Clear Space

Clear space is necessary to provide breathing room around the icon. This space, equivalent to at least half the height or width of the icon block, must be kept clear of any other design element.

**Comment by nc-mhenderson** [comment]
Could leverage some of what is built here:
https://github.com/ndiego/icon-block

**Comment by pikemurdy** [comment]
That's a possibility. I know Chris (and myself) really want to have as few dependencies as possible. What do you mean by 'leverage'? Just using the code found there in our own theme?

**Comment by nc-mhenderson** [comment]
I think we could use this as a head start. There is some additional functionality included this plugin that we would limit.

**Comment by reasterbrooknc** [comment]
@pikemurdy could you see about getting new versions of the svg files of the icon library? 
- The fill and stroke need to be set in the path as an attribute instead of a style tag

Also let us know which color icons need to be available on which backgrounds.

**Comment by pikemurdy** [comment]
Do not put icons on anything other than white. The light gray bar in the interim guidance was an oversight, and we're correcting it.

**Comment by pikemurdy** [comment]
Updated icons:

[Icons Cleaned Up.zip](https://github.com/utkwdn/utkwds/files/14655609/Icons.Cleaned.Up.zip)

**Comment by spworky** [comment]
@nc-mhenderson @reasterbrooknc @pikemurdy Attaching Icons!!

– no extraneous markup is in the attached zip (removed clip-path, defs, ClipPath, etc)
– icons have been simplified to remove invisible chunks
– one color and two color versions

Pleas let me know if you run into any issues and we will take another look. Hopefully these are as clean as you need.

[ut-icons-web-ready.zip](https://github.com/utkwdn/utkwds/files/14795183/ut-icons-web-ready.zip)

**Comment by spworky** [comment]
@reasterbrooknc @pikemurdy I noticed above an ask about the color usage. I believe this is what we are moving forward with:
**On white, On light gray backgrounds**
Two-color icons (smokey outline with orange fills)

**On Smokey background**
One-color icons (orange outline)

**Comment by reasterbrooknc** [comment]
@pikemurdy @spworky we suggest moving forward with only white and light gray background variations. Because we're working with one icon library, every icon we upload to the library will be available for users to select. If we eliminate the Smokey background variation and one-color icons for now, we eliminate the possibility of users mismatching icons + backgrounds. 

Let us know how this sounds. Thanks!

**Comment by nc-mhenderson** [comment]
Can the UTK team look at the following icons. I'm assuming they weren't saved correctly as they are not displaying as nice as the other ones:
* checklist
* coffee
* collaboration
* disability
* giving
* graduate
* international
* knowledge
* safety
* teaching
* ticket
* torch
* undergraduate

![Image](https://github.com/utkwdn/utkwds/assets/107649073/f7332cee-4aff-45b2-85be-7c38f5f4399b)

**Comment by nc-mhenderson** [comment]
I've tracked down this display error as the saved svg not including a `viewBox`

**Comment by spworky** [comment]
I must have gotten a little too zealous with stripping out markup :) Working on getting those to you now.

**Comment by reasterbrooknc** [comment]
Ready for review @pikemurdy. Note that the name in the block inserter will be changed once we have confirmation on the name of the component.

https://wds-dev.utk.edu/icon-text

**Comment by pikemurdy** [comment]
This looks good. What should it be called? Is that a conversation that needs to be had?

**Comment by reasterbrooknc** [comment]
> This looks good. What should it be called? Is that a conversation that needs to be had?

We'd like to call it "icon & text banner," which was what this original component was renamed back in the fall (before it was struck from the system!).
