### ISSUE TITLE
Rename groups in the block inserter

### ISSUE THREAD

**Issue by reasterbrooknc** [utkwdn/utkwds#237]
Hi there @pikemurdy,

Groups can now be named in such a way that their actual pattern name will show in the block inserter (rather than it reading "Group"). Are we clear to add all the component names to the patterns so they show up accurately in the inserter? 

See screenshot. 

![Screenshot 2024-02-01 at 9 24 40 AM](https://github.com/utkwdn/utkwds/assets/111005213/54cc1d69-2673-4149-a70a-0ada9ca16ea4)

**Comment by nc-mhenderson** [comment]
Patterns named with #245.

Some components don't support renaming yet: `cover`, `quote`, `columns`.

**Comment by reasterbrooknc** [comment]
Ready for your review @pikemurdy. Patterns need to be reinserted to reflect the change.

**Comment by pikemurdy** [comment]
Okay. maybe I'm misunderstanding this. I'm still seeing 'Group' on several patterns. The accordions and the 'gallery' patterns at least show up as "Group". But maybe I'm misunderstanding something.

(I'm using what's on the development branch)

https://github.com/utkwdn/utkwds/assets/7902085/4792d12d-3378-4ca8-b90c-6fb23b2626e2

**Comment by reasterbrooknc** [comment]
@pikemurdy this is addressed, if you can take a look!

**Comment by pikemurdy** [comment]
Unless I'm missing something. I just pulled from the repo and rebuilt the development branch.

Still some missing:

## Banners

- [ ] Callout
- [ ] Text and contact textures?

## Content Cards

- [ ] Horizontal 2up white
- [ ] Subject 3up smokey on gray
- [ ] Subject 3up gray on smokey
- [ ] 

## Galleries

- [ ] The Cover one


## Quotes

- [ ] Media & Text- on gray (not sure what this one is supposed to be called)
- [ ] Media & Text - on smokey (not sure what this one is supposed to be called)
- [ ] All of the “Quotes” are just “Quote” with no variation name. (There is no “Quote- White on Smokey” for example).

**Comment by nc-mhenderson** [comment]
**Callout** is a cover, cannot be renamed
**Subject 3up Smokey** is a column, cannot be renamed
**Subject 3up light gray** is a column, cannot be renamed
**Parallax + orange bar** is a cover, cannot be renamed
**Media & text light gray** is a media-text, cannot be renamed
**Media & text Smokey** is a media-text, cannot be renamed
**Quote & media white** is a media-text, cannot be renamed
**Quote & media light gray** is a media-text, cannot be renamed
**Quote & media Smokey** is a media-text, cannot be renamed

**Text & contact Smokey** confirmed renamed
**Horizontal 2up white** added

https://github.com/utkwdn/utkwds/pull/251

**Comment by nc-mhenderson** [comment]
In 6.5 we will be able to rename more patterns.
