### ISSUE TITLE
Issue with Breadcrumb Pattern

### ISSUE THREAD

**Issue by pikemurdy** [utkwdn/utkwds#252]
The breadcrumb pattern could use padding along the bottom of the utk-breadcrumbs-wrapper to display correctly against hero rows that do not have a white background (the hero row background may be a color or a cover image).

Example (artificial): https://cdn.zappy.app/85b7520ed4affaac627fc55da54c270c.png

Proposed solution: https://cdn.zappy.app/781b610ec7f841a937a7eeb476c489c2.png

**Comment by reasterbrooknc** [comment]
Is there a live link for this issue? I'm seeing light gray components bleed properly into the breadcrumb row when I test. @pikemurdy

**Comment by pikemurdy** [comment]
I can't seem to reproduce this. The breadcrumbs seem to now appear _within_ the gray. Has something changed, do you know, @reasterbrooknc ?

**Comment by reasterbrooknc** [comment]
@pikemurdy this is the intended behavior we worked out last year. A page with breadcrumbs and a light gray component at the top (but without a page title) should have the light gray blend into the breadcrumb row to provide more uniformity at the top of the page. Does that make sense?

**Comment by pikemurdy** [comment]
@reasterbrooknc So should we mark this issue closed?
