### ISSUE TITLE
Request to implement Header with Parent Unit and Child Unit both included.

### ISSUE THREAD

**Issue by pikemurdy** [utkwdn/utkwds#253]
Briefly describe either your features request or issue / bug.

As discussed in our check-in, Hillary would like the header to show relationship between parent unit and unit to more easily navigate and to establish relationship hiearchy. There were initial mock-up of this proposal from New City in the first round of work. Leigh believes this is an ask that other colleges will also want to see in the WDS.

Please attach any documentation you would like to share with us.

Screen-Shot-2024-02-22-at-3.17.38-PM.png <https://u8180940.ct.sendgrid.net/ls/click?upn=u001.EX9k7Hh-2B13lSgBq4Agy-2FwUM75j6Ml1c-2B8D7th4zoClvnV4hYC3VrNf-2B3u1uw-2FawRVKzLkv5OpeNaiFYa-2F7JKWfJI3jJkBhTyYDaRAxSpdPQ8MKv7NA9f5-2B9hDg7ZwRqunRIGyirR8REL-2FhkDV7jB4ym4-2B0Bu3DkNQS8k9zW-2BwBALeF55FaTM2lfscmNb2IOMiqLL-2FqXlboLj-2Bo8PqEFWANWL7jwLfzAr7HvZfYYqcVCbBRU-2Bwa6nrwVqbztAQ71rLTdXq3O0GGVyGrNixtASlGPqJfXQ19p3xAd8dcD5-2BC4-3D0SCN_2n1Z6UgJTWNxNVnpAbwshVliEEK7Rv0Duy9WV9mj718l2qJjlOpbhmltYW-2BUJnkaUnQfnhKXSDqk4hrjEF7BoI9tS6i6J1WgW8Jv791iBrgNjPZmtE4C8kMDvNghlCIMT1BOadK-2FlLKG4wLJYjQim74daWyEZ8pKK3E78yArDEXj5vWwuTDYB3qQSrE61GMgrxlMXE2JnSO-2BH44NTVrzhx3K69o-2BRRg9HcfhdRCiGto-3D>

**Comment by nc-mhenderson** [comment]
Used the built in `Tagline` to implement the parent/child relationship.

**Comment by reasterbrooknc** [comment]
Ready for review @pikemurdy. You will see it enabled on wds-dev, and it can be edited from the customizer under "Site Identity > Tagline."

**Comment by pikemurdy** [comment]
Where can I review this?

And can the tagline be a link?

**Comment by reasterbrooknc** [comment]
@pikemurdy as it's built, the tagline can't be a link—this custom functionality could be added in with a few hours dev time.

But if a parent unit link is a technical requirement, we would recommend revisiting the design to add visual clarity that the parent and child link to different places. From a UX perspective, we think users would expect these to link to the same place. 

Let me know your thoughts.

**Comment by pikemurdy** [comment]
The parent unit must be navigable. Our testing in the past didn't show that folks thought it was all the same, IIRC.

We've seen a lot of use cases for this and it's always been a part of our site. When you start to think about departmental "sites" that are subsites of a network... it is used as a way to get back to the college when you click into a departmental site.

**Comment by pikemurdy** [comment]
Okay.
