### ISSUE TITLE
Make images optional in Stacked & Contact card patterns

### ISSUE THREAD

**Issue by pikemurdy** [utkwdn/utkwds#257]
Need some card patterns that do not require images. 2-up/3-up

**Comment by reasterbrooknc** [comment]
More of an info card.

**Comment by reasterbrooknc** [comment]
- Make image optional in Stacked Card and Contact Card

**Comment by reasterbrooknc** [comment]
Testing across browsers, removing images from these patterns isn't presenting spacing issues: https://wds-dev.utk.edu/no-image-cards cc @pikemurdy for review
