### ISSUE TITLE
Sidebar navigation

### ISSUE THREAD

**Issue by pikemurdy** [utkwdn/utkwds#258]
Briefly describe either your features request or issue / bug.

Need a vertical side menu for deeper content.

Examples of what folks are doing, not saying we should copy this look, just functionally:

https://tickle.utk.edu/academics/advising/

https://artsci.utk.edu/newsroom/

(Looks like they were inspired by each other)

**Comment by pikemurdy** [comment]
From Sam:

Here is another vertical navigation for deeper content / interior pages: 

https://utkosstg.wpenginepowered.com/registration-records/academic-policies/

We're using this on most One Stop internal pages. It's modeled off of the main navigation styles in terms of hover and current page.

**Comment by reasterbrooknc** [comment]
@nc-mhenderson add hover effect: Light gray background + nudging to the right a couple px

**Comment by reasterbrooknc** [comment]
Ready for review @pikemurdy https://wds-dev.utk.edu/about/campus-locations/knoxville-campus

**Comment by pikemurdy** [comment]
Approved
