### ISSUE TITLE
New Pattern: "Points of Pride" strip/stats block

### ISSUE THREAD

**Issue by pikemurdy** [utkwdn/utkwds#259]
Approved design: 

[utk fast facts.zip](https://github.com/utkwdn/utkwds/files/15392582/utk.fast.facts.zip)

![Image](https://github.com/utkwdn/utkwds/assets/111005213/e8e0fe06-3458-4463-a906-def78bb08a2f)

--
A pattern to show brag points.

Similar to what's in gray, halfway down the page here:
https://www.utk.edu/academics

Things to consider:
- Could use icons?
- Could use big number with special typography.

**Comment by reasterbrooknc** [comment]
Q2/Q3, if possible.

**Comment by reasterbrooknc** [comment]
- Open questions about font and variations. Recommend no icons.

**Comment by pikemurdy** [comment]
I have no recommendation on fonts beyond the sofia guidance. I know from creative they want to use sofia sparingly. I think the multiple variations thing gets complicated as it seems like it depends on what's around the component as to what looks nice.

Some examples "special" typography are in the wild, like:

<img width="1587" alt="Screenshot 2024-04-30 at 8 11 36 AM" src="https://github.com/utkwdn/utkwds/assets/7902085/76594f2b-5951-45e2-80d7-f67e12925008">

(Note the orange drop shadow)
We also use that styling on our home page at the bottom. I don't have a strong opinion, just to know: It's out there.

I'm also in favor of keeping things simple, clean. _Do less._ 😉

But it's up to the designers to recommend exactly what it should be.

**Comment by pikemurdy** [comment]
We probably should have some variations on the number of points. Not sure if that needs to be variations on the pattern, or just a mechanism to add/remove points. Meaning, sometimes there may be four points of pride, sometimes three, etc.

**Comment by rdelaude** [comment]
Update for default text to the component is here on https://brand-dev.utk.edu/web-design-system/points-of-pride-component-test/ in the top pattern (white version, starting with "Big text").
