### ISSUE TITLE
Link group component

### ISSUE THREAD

**Issue by reasterbrooknc** [utkwdn/utkwds#263]
##Presenting revised recommendation to UTK team today. Related to #247

**Comment by reasterbrooknc** [comment]
![Image](https://github.com/utkwdn/utkwds/assets/111005213/1a5f9f48-4608-4a65-983f-acbae5bb931d)

**Comment by reasterbrooknc** [comment]
### Requirements
- Name: Link group
- Category: Links
- Wide-width
- Requires standalone link and single-column link list. Single-column link list is not its own pattern and is only available within this pattern—and possibly other patterns (TBD). 
- Only white background
- No heading on pattern
- Rollover state: Arrow moves forward, text turns Smokey (similar to in-page navigation links)
- Build with CSS columns instead of WP columns
- Use block style to toggle between 2-up and 3-up
- Responsiveness: 
-- No spaces between columns when it stacks. 
-- One breakpoint so no orphans. 
-- As text wraps, gutters stay the same.

**Comment by nc-mhenderson** [comment]
@rdelaude Placeholder text can be added here.

**Comment by rdelaude** [comment]
@nc-mhenderson 

Description: List of links in 2 or 3 columns
Keywords: links, link list, link group, collection, columns, columned, 2, 3
Default Text:

2-Column Link Group
Space for paragraph text to describe what this group is about, if needed. 
Link 1
Link 2
Link 3
Link 4
Link 5

3-Column Link Group
Space for paragraph text to describe what this group is about, if needed. 
Link 1
Link 2
Link 3
Link 4
Link 5
Link 6
Link 7
Link 8
