### ISSUE TITLE
New Pattern: Video Embedder

### ISSUE THREAD

**Issue by pikemurdy** [utkwdn/utkwds#268]
Default video: https://www.youtube.com/watch?v=jIOicdbm2bs

--
From Engineering:

"I think there should be additional components for video blocks. Right now all I see are blocks with images. To create a video block, you have to create it from scratch."

To be clear, this is a way to embed a YouTube video, not a background textural video.

**Comment by reasterbrooknc** [comment]
Can Media & Image component accommodate video?

**Comment by reasterbrooknc** [comment]
- Assuming we can use native WP embed functionality. Recreate 50/50s with video functionality?

**Comment by pikemurdy** [comment]
Other examples:

https://brand.utk.edu/web-design-system/index.php?gf-download=2024%2F04%2Futk-content-with-framed-video-texture-simple-bold.png&form-id=1&field-id=7&hash=fe46f55780cb6f09be4118ed2ad700eea9064ba1400e4380e9e7c3923eb01989

https://brand.utk.edu/web-design-system/index.php?gf-download=2024%2F04%2Futk-content-with-framed-video-texture.png&form-id=1&field-id=7&hash=dbb4b323324a56a8336c3762a49703de8cf058946532009914aa064a20d94a47

**Comment by pikemurdy** [comment]
Yes, the more we can use native WP functionality the better.

**Comment by reasterbrooknc** [comment]
https://brand.utk.edu/web-design-system/component-library/50-50-header-with-fancy-link/ for reference

**Comment by pikemurdy** [comment]
I think this works. I was confused... I assume the new pattern called "video & text CTA white"... if so I think it works fine. We'll need some docs.

**Comment by reasterbrooknc** [comment]
@pikemurdy all versions are available here: https://wds-dev.utk.edu/video-text-with-cta 

Looping in @lshoe here for thoughts on documentation. This is a replica of the Media & Text with CTA but with the option to embed a video. While it is its own pattern, for documentation purposes, we are seeing it as a variation of Media & Text. Does that make sense to you? If so, we'd like to propose naming/renaming those pattern variations as follows:

- Media & Text with CTA
- Image & text, light gray
- Text & image, light gray
- Image & text, white
- Text & image, white
- Video & text, light gray 
- Text & video, light gray
- Video & text, white
- Text & video, white

**Comment by pikemurdy** [comment]
These all make sense to me, but would like @lshoe to weigh in.
