### ISSUE TITLE
Single link 

### ISSUE THREAD

**Issue by reasterbrooknc** [utkwdn/utkwds#274]
### Requirements
- Rollover state: Arrow moves forward, text turns Smokey (similar to in-page navigation links)
- On Smokey, text turns white
- No gray line
- Available in block inserter
- Basic paragraph spacing

**Comment by nc-mhenderson** [comment]
@rdelaude Also need starter content here. Also would like description text.

**Comment by rdelaude** [comment]
Description: For medium emphasis, like at the end of a paragraph. Limit to 30 characters to keep it “clickable.”
Keywords: links, link, single, standalone, fancy
Default Text: Single link
