### ISSUE TITLE
Change case on new hero

### ISSUE THREAD

**Issue by pikemurdy** [utkwdn/utkwds#295]
The H1 on the full-width hero (https://brand.utk.edu/web-design-system/component-library/full-width-hero/) should be all caps, per Sofia guidelines.

**Comment by reasterbrooknc** [comment]
Can heading still be all caps if optional Sofia superheading is removed? @pikemurdy checking with Stephanie.

**Comment by reasterbrooknc** [comment]
Keep it all caps, per @pikemurdy in 5/15 meeting.

**Comment by reasterbrooknc** [comment]
Looks good to me. cc @pikemurdy for confirmation: https://wds-dev.utk.edu/full-width-hero

**Comment by pikemurdy** [comment]
Approved
