### ISSUE TITLE
Style core blocks

### ISSUE THREAD

**Issue by pikemurdy** [utkwdn/utkwds#297]
[Finalized Figma for core block styles
](https://www.figma.com/design/OnZKcZ4pVbDLxuGThDodig/UTK-%7C-Design-v06?node-id=11205-4778&t=NY7bS1hrJ5PxjX3q-1)

--
Probably a styling of the HR would suffice. Currently there's options for dots (which are off-brand) or squares.

Previously, we had a couple of options. One full-width and chunky. One sorta short one.

https://thehill.utk.edu/documentation/navigation-orangehash/

https://thehill.utk.edu/documentation/navigation-orangetouch/

They worked really well for adding orange and breaking up long pages of text.

![admissions-separator-orange-accordion](https://github.com/utkwdn/utkwds/assets/7902085/bcef23c3-8d3c-4ae4-8596-d7b54aa2baa4)

**Comment by reasterbrooknc** [comment]
Nail down/clean up variations on separator.

**Comment by reasterbrooknc** [comment]
@pikemurdy these are available for review here: https://wds-dev.utk.edu/core-blocks 

Note that I'm awaiting final design QA but wanted to get your eyes on them as well.

**Comment by pikemurdy** [comment]
On the "details" element...there seems to be two arrows and it looks awkward.

**Comment by reasterbrooknc** [comment]
@pikemurdy we have two details inserted back to back on the page, is this what you're seeing? Or do you see something that looks more like a bug?
![Screenshot 2024-06-21 at 1 01 05 PM](https://github.com/utkwdn/utkwds/assets/111005213/dd505436-b03a-4858-a830-36787a99a8eb)

**Comment by pikemurdy** [comment]
That would be okay. But in Safari 17.5 on the Mac and iOS 17.5.1, I'm seeing it differently. Seems to work in Firefox and Chrome.

![IMG_5FCDE6CCAFEF-1](https://github.com/utkwdn/utkwds/assets/7902085/c0dd6a1d-0fae-422c-873f-6206794f58ef)


<img width="268" alt="Screenshot 2024-06-21 at 1 33 31 PM" src="https://github.com/utkwdn/utkwds/assets/7902085/537592dd-f5a2-49dd-a8e1-8b41f8bb4e47">

<img width="841" alt="Screenshot 2024-06-21 at 1 33 36 PM" src="https://github.com/utkwdn/utkwds/assets/7902085/aec6eefc-e555-4dfa-9126-0c8e6f06a4da">

**Comment by reasterbrooknc** [comment]
@pikemurdy this should be fixed, can you take another look?

**Comment by pikemurdy** [comment]
That looks good now.

**Comment by nc-mhenderson** [comment]
Need to scope `li` when WP adds class in next version.

**Comment by reasterbrooknc** [comment]
> Need to scope `li` when WP adds class in next version.

Closing issue but opening new one to address this post-6.6.
