### ISSUE TITLE
New variation: Stack card on orange full width bar

### ISSUE THREAD

**Issue by pikemurdy** [utkwdn/utkwds#299]
Groups of cards overlaid on orange full width bar. We have lots of quotes like this, but might be nice to get orange behind some of these groups as well.

Examples of these:

https://www.utk.edu/about/traditions-history

https://www.utk.edu/about/quick-facts

https://admissions.utk.edu/college-preparation/

![utk-cards-overlay-orange-02](https://github.com/utkwdn/utkwds/assets/7902085/1eb85667-4de1-4e80-81cc-bc55eae07dde)
![admissions-cards-overlay-orange](https://github.com/utkwdn/utkwds/assets/7902085/896c200f-4dd7-4b51-86a7-e6b361c12943)

**Comment by reasterbrooknc** [comment]
Discuss after alignment meeting on WDS prioritization.

**Comment by reasterbrooknc** [comment]
Looks good. Test pages for review:
- https://wds-dev.utk.edu/newcity-testing/kitchen-sink
- https://wds-dev.utk.edu/test-page-stack-card-patterns

**Comment by reasterbrooknc** [comment]
Ready for your review @pikemurdy

**Comment by pikemurdy** [comment]
This is good.
