### ISSUE TITLE
Accordion header text spacing

### ISSUE THREAD

**Issue by pikemurdy** [utkwdn/utkwds#305]
**Describe the bug**
This issue has been encountered on the new One Stop website.

Accordion heading text needs spacing between edge of text and the &#039;+&#039; icon.

**Page URL**

**WDS Theme Version**
1.1.3

**To Reproduce**
1. Create and accordion fold with a long title.

**Expected behavior**
a bit more space from the +

**Screenshots**
 
![164d7c247bd02db205c921200281fcb9](https://github.com/utkwdn/utkwds/assets/7902085/4b05c34e-2249-433e-a25d-4a458f757429)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacOS
 - Browser : Chrome, Firefox and Safari

**Comment by reasterbrooknc** [comment]
Looks good on the [new version](https://wds-dev.utk.edu/?page_id=63976&preview=true).

[Old version](https://brand.utk.edu/web-design-system/?page_id=545&preview=true) on brand site for reference.

**Comment by pikemurdy** [comment]
Yes. Looks good.
