### ISSUE TITLE
Margins too tight

### ISSUE THREAD

**Issue by pikemurdy** [utkwdn/utkwds#307]
**Describe the bug**
Not enough padding or margin.

**Page URL**

https://brand.utk.edu/web-design-system/component-library/50-50-header-with-fancy-link/

https://brand.utk.edu/web-design-system/component-library/text-media-background-banners/

**WDS Theme Version**

Current.

**Expected behavior**
These two patterns could use more padding or margin between the paragraph block and the link list.

**Screenshots**
Screenshot attached showing the padding setting we changed to provide more spacing.

![Screen-Shot-2024-05-15-at-9 17 53-AM](https://github.com/utkwdn/utkwds/assets/7902085/d8dc4d45-a2ec-4382-ac84-1bb5a7c10b33)

**Desktop (please complete the following information):**

All Browsers and Operating Systems.

**Comment by reasterbrooknc** [comment]
This needs to change from a "fancy link list" to a CTA link. Then adjust spacing.

**Comment by reasterbrooknc** [comment]
I believe this is fixed on both patterns, per this page: 

- https://wds-dev.utk.edu/?page_id=64019&preview=true 

Can you confirm @pikemurdy? 

But it is still an issue on the contact card banner, per #129

**Comment by pikemurdy** [comment]
Okay. these look right.
