### ISSUE TITLE
H3 is oddly breaking Horizontal Single Light Grey

### ISSUE THREAD

**Issue by pikemurdy** [utkwdn/utkwds#324]
**Describe the bug**
H3 is oddly breaking Horizontal Single Light Grey

**Page URL**

**WDS Theme Version**
1.1.4

**To Reproduce**
1. Use the Horizontal Single Light Grey pattern, and add a moderately long word in the H3.

**Expected behavior**
H3 is breaking oddly at smaller breakpoint sizes

**Screenshots**
![horiz-single-h3-breaking](https://github.com/utkwdn/utkwds/assets/7902085/87be5e8e-345d-4c19-bb2f-52a3031db16b)

**Desktop (please complete the following information):**
safari ios

**Smartphone (please complete the following information):**
 - iPhone

**Comment by reasterbrooknc** [comment]
Rewrite the rule to target all heading levels.

**Comment by pikemurdy** [comment]
When it does force a break, can it have a hyphen?

**Comment by reasterbrooknc** [comment]
Related to #405, which should be addressed in 1.2.4. Closing!
