### ISSUE TITLE
Correct 4 patterns on documentation site to align with Link Guidance

### ISSUE THREAD

**Issue by pikemurdy** [utkwdn/utkwds#326]
Multiple patterns are still built to display with three fancy links and/or stacked text links. They need to be corrected according to our guidance using a link group or maybe single text links?

Patterns IDed so far include:

1. [Contact Card Banner](https://brand.utk.edu/web-design-system/component-library/content-with-fancy-links/) aka Text & contact Smokey

- Adjust to one CTA link

2. [Horizontal card](https://brand.utk.edu/web-design-system/component-library/horizontal-card/)

- Adjust to single link

3. [Stacked card](https://brand.utk.edu/web-design-system/component-library/stacked-card/)

- Adjust from text link list to single link
- Change default paragraph text to, "Stack Cards can be used to set important information apart from the rest of the page and collect links related to a single subject."

4. [Text & Media + background banners](https://brand.utk.edu/web-design-system/component-library/text-media-background-banners/)

- Adjust from CTA links to to single link
- Change default paragraph text to “This pattern can be used to set important information apart from the rest of the page and collect links related to a single subject. Works well positioned above a footer.”

5. [Media & Text with CTA and Text & Media with CTA](https://brand.utk.edu/web-design-system/component-library/50-50-header-with-fancy-link/)

- Delete last 2 CTA Links from pattern (so only one is there by default). 
- Change default paragraph text to “The Media & Text with CTA pattern is designed to fill the hero area of a high-level landing page, to orient users to what your page is about.”

6. [Media & text banner](https://brand.utk.edu/web-design-system/component-library/media-text-banner/)

- Adjust from CTA link to single link
- Change default paragraph text to “This pattern can be used to set important information apart from the rest of the page and/or collect links related to a single subject.”

ETA: We have this [guidance from Rachel](https://docs.google.com/document/d/1QgVcvPwyIFBZK7TldHz-Nyrn2zPZQBc2dzFR9CJysRs/edit?usp=sharing) that I don't think was ever signed off on.

**Comment by reasterbrooknc** [comment]
Ready for review @pikemurdy.
