### ISSUE TITLE
Contact Cards not staying uniform when people with longer titles are added.

### ISSUE THREAD

**Issue by pikemurdy** [utkwdn/utkwds#327]
**Describe the bug**
The contact cards are pretty tiny and therefore some of our faculty with mulitiple titles end up having taller cards than the one next to them. Even with adding hard breaks to the card next to it to create the same size, that causes an issue with uniformity throughout. 

**Page URL**
https://wds-stg.utk.edu/about/directory

**Desktop (please complete the following information):**
 - Safari and Chrome

**Screenshots:**
![Screenshot-2024-05-28-at-3 28 10-PM](https://github.com/utkwdn/utkwds/assets/7902085/c6c2fb45-9319-4905-b04e-24ca6f1c8866)

**Comment by pikemurdy** [comment]
The only one at the moment: https://cci-dev.utk.edu/about__trashed/faculty-and-staff-directory/

**Comment by nc-mhenderson** [comment]
Test page
https://wds-dev.utk.edu/?page_id=64058&preview=true

**Comment by reasterbrooknc** [comment]
Ready for QA @pikemurdy

**Comment by pikemurdy** [comment]
The front-end cards look good and behave as expected. It looks like the editor is stretched and odd in Safari 17.5.

Looks fine in Firefox and Chrome, but not exactly as the front end. Not sure how hard of a fix this is.

<img width="1744" alt="Screenshot 2024-07-19 at 1 55 38 PM" src="https://github.com/user-attachments/assets/003ccde5-fb48-418d-a98c-dde0468c8d1e">
<img width="1616" alt="Screenshot 2024-07-19 at 1 56 54 PM" src="https://github.com/user-attachments/assets/5c3ac94b-4bec-4bf3-9fd3-8dd5d60655d4">


<img width="1488" alt="Screenshot 2024-07-19 at 1 53 43 PM" src="https://github.com/user-attachments/assets/a6a72fb4-a8f0-48d4-ac1d-91a72ac9e5f7">

**Comment by reasterbrooknc** [comment]
Looks good to me. @pikemurdy can you test in Safari again?
