### ISSUE TITLE
Add program page template to WDS

### ISSUE THREAD

**Issue by reasterbrooknc** [utkwdn/utkwds#332]
- [Guidelines](https://brand.utk.edu/web-design-system/general-guidelines/program-pages/)
- [Page template in action](https://wds-dev.utk.edu/programs-template-02)

**Comment by reasterbrooknc** [comment]
Ready for your review @pikemurdy. You can see it [here](https://wds-dev.utk.edu/program-page-template) and/or add it to a blank page from the template inserter.

**Comment by pikemurdy** [comment]
Yeah. But think we'd need a version with a smaller headline. When you get into a program with a long name like "Entomology, Plant Pathology, and Nematology" it gets a bit much.
