### ISSUE TITLE
Main navigation tweaks

### ISSUE THREAD

**Issue by pikemurdy** [utkwdn/utkwds#334]
**Describe the bug**
Main nav items are being cutoff the screen at breakpoints between 1171px and 1440px wide. The mobile nav is not kicking in soon enough. ETA that orange line should appear on child items of main nav items.

**Page URL**
https://cci-dev.utk.edu
https://csw-dev.utk.edu/academics-and-programs/graduate-programs/masters-of-science-in-social-work/

**WDS Theme Version**
1.1.4

**Expected behavior**
Menu goes into 'mobile view' earlier?

**Screenshots**
![nav-breakpoint-issue-01](https://github.com/utkwdn/utkwds/assets/7902085/9f271c38-4893-407f-9561-e985c010c4ad)

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser [safari]

**Comment by reasterbrooknc** [comment]
Per 9/18 meeting, Purdy will have internal convos about how this impacts IA recs.

**Comment by reasterbrooknc** [comment]
Per 10/30 meeting, put dropdown carat underneath the text, as short-term fix.
