### ISSUE TITLE
New variation: Content with Fancy Links in Light Gray and White versions

### ISSUE THREAD

**Issue by pikemurdy** [utkwdn/utkwds#351]
Can we generate variations of this specific pattern:

https://brand.utk.edu/web-design-system/component-library/content-with-fancy-links/

Clients are using this at the bottom of the page which is too much dark background next to the footer. We&#039;d like to see a white and a light gray version.

**Comment by reasterbrooknc** [comment]
For white variation, use light gray contact card. For light gray variation, use white contact card.

**Comment by reasterbrooknc** [comment]
Test pages for review:
- https://wds-dev.utk.edu/newcity-testing/kitchen-sink
- https://wds-dev.utk.edu/test-page-contact-card-banner-patterns

**Comment by reasterbrooknc** [comment]
Ready for your review @pikemurdy
