### ISSUE TITLE
Localist widget

### ISSUE THREAD

**Issue by reasterbrooknc** [utkwdn/utkwds#367]
Generate list of technical requirements so that we can scope the lift. 

* [Current UTK calendar](https://calendar.utk.edu/)
* [Localist Widget Builder](https://calendar.utk.edu/help/widget)

Add in display options and display limits.

**Comment by reasterbrooknc** [comment]
Investigate whether Charlie's code is a reasonable option for how to get field values from Localist: https://github.com/utkwdn/utksds-plugin/tree/main/src/calendar

**Comment by nc-mhenderson** [comment]
## Defaults 
* 10 results
* 7 days
## Attributes
* `results` number < 10
* `departments` comma separated values
* `groups` comma separated values
* `days` number
* `tags` comma separated values
* `target` 1,y,yes,true

## Example Usage
```
<!-- /wp:shortcode -->
[localist_widget results=3 department=socialwork tags="continuing education,general events"]
<!-- /wp:shortcode -->
```

https://help.concept3d.com/hc/en-us/articles/11942564300819-Widgets

**Comment by reasterbrooknc** [comment]
@pikemurdy we're still doing some internal review, but wanted to get this in front of you today: https://wds-dev.utk.edu/newcity-testing/localist-widget

**Comment by pikemurdy** [comment]
This is good for now.
