### ISSUE TITLE
Slate form embed

### ISSUE THREAD

**Issue by reasterbrooknc** [utkwdn/utkwds#369]
Exists in the theme now but should be revisited and documented.
Asks for ID and URL for embed. Links to piece of javascript that Slate provides.

- [ ] Need example forms to target and QA.
- [x] Send Purdy an example of what the shortcode looks like. 

https://wds-stg.utk.edu/future-students/online-masters#online-masters-request

**Comment by reasterbrooknc** [comment]
@pikemurdy here is the code you can use to test out the current state of the embed 
[slate_form id="[number here]" register_url="[register url here]"]

**Comment by pikemurdy** [comment]
I'm guessing this is good to go... but I've not got it to load a form.

But I'm not sure what to put in the "Register URL here" variable should be.

https://wds-stg.utk.edu/?page_id=63442&preview=true

**Comment by nc-mhenderson** [comment]
`[slate_form id="form_d2ee93c9-0a98-4bdf-b5bd-6631518b29b6" register_url="https://apply.gradschool.utk.edu/register/"]`

**Comment by pikemurdy** [comment]
So... dumb question... how do you get the register url? Usually when I've received embed code, it's just some JS with an ID.

**Comment by nc-mhenderson** [comment]
@pikemurdy This was part of the embed code I got from the slate embed code. It seems like it would be configured based on what site the form is intended to appear on. It is hard to know the differences without seeing other slate embeds, I don't have visibility into that system.
