### ISSUE TITLE
Gallery pattern bug

### ISSUE THREAD

**Issue by reasterbrooknc** [utkwdn/utkwds#371]
**Describe the bug**
All four variations of the gallery pattern are displaying improperly. 

**Page URL**
https://wds-dev.utk.edu/test-page-gallery-patterns

**WDS Theme Version**
1.1.5

**To Reproduce**
1. Visit https://wds-dev.utk.edu/test-page-gallery-patterns or insert gallery patterns on any page to see the issue. This also happens on the documentation site, fwiw.

**Expected behavior**
On the small-large variations, the small image shouldn't abut the edge of the screen, there should be a margin. On the large-small variations, there should be a margin between the two images—they're squished together right now. 
[Figma file](https://www.figma.com/design/OnZKcZ4pVbDLxuGThDodig/UTK-%7C-Design-v06?node-id=4515-19790&t=AflLyerTWj6TUWBa-4)

**Screenshots**
[screencapture-wds-dev-utk-edu-test-page-gallery-patterns-2024-07-03-12_45_56.pdf](https://github.com/user-attachments/files/16088115/screencapture-wds-dev-utk-edu-test-page-gallery-patterns-2024-07-03-12_45_56.pdf)

**Desktop (please complete the following information):**
 - OS: Sonoma 14.5
 - Browser [e.g. chrome, safari]: Observed in Chrome, Safari, and Firefox

**Smartphone (please complete the following information):**
 - Haven't checked mobile yet

**WordPress Plugins Installed**
n/a

**Additional context**
n/a

**Comment by reasterbrooknc** [comment]
Ready for your review @pikemurdy

**Comment by pikemurdy** [comment]
This looks good.
