### ISSUE TITLE
Update tagline to read site title

### ISSUE THREAD

**Issue by reasterbrooknc** [utkwdn/utkwds#373]

**Comment by reasterbrooknc** [comment]
We're hesitant to change this core WP field name—@nc-mhenderson strongly recommends against it. All WP documentation that exists refers to "tagline." 

To implement, would need to generate translation file so that all references to "tagline" are updated.

**Comment by pikemurdy** [comment]
I understand. I don't want to change core.

But 'tagline' is weird for this. It's not a tagline, it's a parent unit. And it's caused confusion. Is there another route?

Also: Do we even know if Site Admins have the ability to edit this field (or section) or is it restricted to Super Admins like the Custom CSS section?

**Comment by reasterbrooknc** [comment]
> I understand. I don't want to change core.
> 
> But 'tagline' is weird for this. It's not a tagline, it's a parent unit. And it's caused confusion. Is there another route?
> 
> Also: Do we even know if Site Admins have the ability to edit this field (or section) or is it restricted to Super Admins like the Custom CSS section?

Another option would be to re-implement it by adding a field to the Customizer. So, instead of using the tagline, we'd add a field that said "parent," e.g. But it would be edited in the same place and in the same way as the tagline currently is.

**Comment by pikemurdy** [comment]
I am more comfortable with that.

**Comment by reasterbrooknc** [comment]
Ready for your review @pikemurdy
