### ISSUE TITLE
Full width hero spacing

### ISSUE THREAD

**Issue by nc-mhenderson** [utkwdn/utkwds#384]
**Describe the bug**
full width content is covering blocks below it
- [ ] within block editor
- [ ] on frontend
- [ ] set new default in pattern for min height to 50vh

**Page URL**

**WDS Theme Version**
1.1.5

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**WordPress Plugins Installed**
If applicable

**Additional context**

![Image](https://github.com/user-attachments/assets/3d389e01-ef77-4e62-8d4c-901663269f6f)

**Comment by reasterbrooknc** [comment]
Thought this was limited to the block editor, but seeing a frontend display issue here: https://cecs-dev.utk.edu/test-page/
- Test this with other components beneath the full-width hero

**Comment by reasterbrooknc** [comment]
Bugs are fixed, but having Sara and Rodger chime in on getting this to respond a bit better on mobile.

**Comment by reasterbrooknc** [comment]
@pikemurdy this is also ready for your review: https://wds-dev.utk.edu/full-width-hero-breadcrumbs

Please note that we also added min height to the image to address concerns about mobile responsiveness.

**Comment by pikemurdy** [comment]
This looks better.
