### ISSUE TITLE
Redesign Tabs

### ISSUE THREAD

**Issue by pikemurdy** [utkwdn/utkwds#386]
**Describe the bug**
The tabs visual is looking out of place. What about a new look? Britney with Tickle has designed an alternative (Screenshot attached.)

**Screenshots**
https://brand.utk.edu/web-design-system/index.php?gf-download=2024%2F07%2FTCE-Active-Site.png&form-id=1&field-id=7&hash=d2e1af777ce95446eaf2eaa2e458b3226458de582363501f439990771db9b59b

https://brand.utk.edu/web-design-system/index.php?gf-download=2024%2F07%2FDev-Site.png&form-id=1&field-id=7&hash=9412ed3a844cade26f8890764f7fdb5d528bec611d6ebe8eb5c8acdfddb6cb5c

**Comment by reasterbrooknc** [comment]
Hi @pikemurdy, would the tabs design that we have on Storefront work for this? https://brand.utk.edu/web-design-system/component-library/statement/

**Comment by reasterbrooknc** [comment]
Tabs are incorporated into new Storefront and are in QA. Will be incorporated into release in 1.2.4.

**Comment by reasterbrooknc** [comment]
Ready for review @pikemurdy https://wds-dev.utk.edu/data-elements/tabs

**Comment by pikemurdy** [comment]
This is good.
