### ISSUE TITLE
Rendering of the interior nav is poor when made sticky

### ISSUE THREAD

**Issue by pikemurdy** [utkwdn/utkwds#392]
**Describe the bug**
When the internal nav component is made sticky, there is no background color, so text behind it bleeds through

**WDS Theme Version**

1.1.5

**To Reproduce**
1. Place the sticky nav and add items
2. make it sticky, and start scrolling

**Expected behavior**
There should be some kind of background on it to prevent seeing elements behind it.

**Screenshots**
![screenshot_2024-07-26_at_3 32 58_pm_720](https://github.com/user-attachments/assets/3162f69b-1b99-4bc8-a3fa-2cd0d04405eb)

**Additional context**
A working version:
https://admissions.utk.edu/undergraduate-application/first-year-student/
https://cci-dev.utk.edu/home/academics-and-programs/graduate-certificates

**Comment by reasterbrooknc** [comment]
This is ready for review @pikemurdy. 
https://wds-dev.utk.edu/test-page-in-page-navigation-patterns

**Comment by reasterbrooknc** [comment]
> In safari, the in-page nav seems to not be 'sticking' to the top of the page, but rather a handful of pixels below the top:
> 
> <img alt="Screenshot 2024-08-27 at 8 37 57 AM" width="1186" src="https://private-user-images.githubusercontent.com/7902085/361806254-1e8860ef-5983-4c0b-89db-20cff8a42a78.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3NjM4NzUsIm5iZiI6MTcyNDc2MzU3NSwicGF0aCI6Ii83OTAyMDg1LzM2MTgwNjI1NC0xZTg4NjBlZi01OTgzLTRjMGItODlkYi0yMGNmZjhhNDJhNzgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjdUMTI1OTM1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjM4N2NjYjk2NTFjNDY5YTU0OWMzMTYzMDlhMWUxZjY3NDA3MjgzY2U3ZTEyNzIwZjc5MzQ1ZDRiODIxYjI5MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.IR-4_39lpsmeEhkIvBVnINNigxfBfZ246UQ5SCUjVyQ">

Thanks, Purdy! This is fixed: https://wds-dev.utk.edu/test-page-in-page-navigation-patterns

**Comment by pikemurdy** [comment]
Looks good.
