### ISSUE TITLE
Vanishing Breadcrumbs with new release

### ISSUE THREAD

**Issue by pikemurdy** [utkwdn/utkwds#399]
**Describe the bug**
Breadcrumbs disappear on the pages using the hero component that features text on one side and photo on the other side - may just be with the light gray variation.

There also is something odd going on with that row in that it expands off the edge of the page on the right creating a horizontal scroll.

**Page URL**
[2Fwe5gIRK73pF6WUeDjaPXKv8](https://u8180940.ct.sendgrid.net/ls/click?upn=u001.EX9k7Hh-2B13lSgBq4Agy-2Fwe5gIRK73pF6WUeDjaPXKv8-3D7OO4_2n1Z6UgJTWNxNVnpAbwshVliEEK7Rv0Duy9WV9mj718l2qJjlOpbhmltYW-2BUJnka-2BYGoiKkLaV8Lcqga8yVJmPzg-2F-2F3-2FQvATd9TsCgOPrVPd0BdNpMAkRQkSfOYBw6-2F-2F4cWGsjbqruTdCkQMyN87-2BSHJJfZoRBmkaispg1l7TrH-2FBj7h5zmjDR-2BYvBuNn48MLIZuS-2FOcgCjaamhfwTnBBITM3Hg-2Foyf8as0HrnexfL4-3D)

**WDS Theme Version**
1.2

**Comment by reasterbrooknc** [comment]
Happening with white variation of 50/50 on no breadcrumbs page template: https://wds-dev.utk.edu/newcity-testing/breadcrumbs-bug

**Comment by reasterbrooknc** [comment]
> Happening with light gray variation of 50/50 on no breadcrumbs page template: https://wds-dev.utk.edu/newcity-testing/breadcrumbs-bug
> 
> ![Image](https://private-user-images.githubusercontent.com/111005213/358388800-b5873d84-e0fc-4cfd-aac9-9f0f734fcc3d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4MjAzMTQsIm5iZiI6MTcyMzgyMDAxNCwicGF0aCI6Ii8xMTEwMDUyMTMvMzU4Mzg4ODAwLWI1ODczZDg0LWUwZmMtNGNmZC1hYWM5LTlmMGY3MzRmY2MzZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNlQxNDUzMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMDM3NGNhNGMyNDRiZDJiMGNjMTNlYmZhZjY3YTgwZDY5NjkyN2Q1NGUxMWQ0YTZiZTI5YTA0NGY5YzRjMmE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nKxOxOgwQapQrXxGq-7CT9aBHk4qfDNutdhzmfpW6mI)

This is ready for your review @pikemurdy.
