### ISSUE TITLE
Horizontal scroll on quote and gallery patterns

### ISSUE THREAD

**Issue by pikemurdy** [utkwdn/utkwds#403]
**Describe the bug**
There is a horizontal scroll on any pages that have a utkwds-quote-media-orange pattern.
Seeing it on gallery patterns also.

**WDS Theme Version**
WDS 1.2

**To Reproduce**
[vidyard](https://share.vidyard.com/watch/y1KGHiKcZ8SiAoBg5XMj72)
We have not thoroughly tested to see if this bug is present in other quote type patterns.
- https://wds-dev.utk.edu/test-page-quote-patterns
- https://wds-dev.utk.edu/test-page-gallery-patterns

**Expected behavior**
No horizontal scroll

**Desktop (please complete the following information):**
All

**Comment by nc-mhenderson** [comment]
width on `:before` element

**Comment by pikemurdy** [comment]
Also found here: https://cci-dev.utk.edu/academics-and-programs/graduate-certificates/

**Comment by reasterbrooknc** [comment]
Ready for your review @pikemurdy 
https://wds-dev.utk.edu/newcity-testing/kitchen-sink

**Comment by pikemurdy** [comment]
Looks right.
