### ISSUE TITLE
Headings on mobile

### ISSUE THREAD

**Issue by pikemurdy** [utkwdn/utkwds#405]
**Describe the bug**
Headers in boxes whether it be cards or heroes are broken and text displays outside of boxes on mobile

**Page URL**

Kinda happens all over the place, but for sure:

https://csw.utk.edu

https://csw.utk.edu/academics-and-programs/

Screenshots below.

**WDS Theme Version**
1.2.2

**Expected behavior**
Better handling of long words in headings—not being prescriptive here. Maybe adjusting the margins or padding. Maybe scaling the type smaller. Maybe both. 

**Smartphone (please complete the following information):**
iPhone 14 Pro
Safari in iOS 18.0.1

**Screenshots**

![IMG_7479](https://github.com/user-attachments/assets/fb7f15e8-ee50-4fd0-af98-ca8c2354be20)
![IMG_7480](https://github.com/user-attachments/assets/9c5a82b1-4e4a-4f6a-900e-215c98dc07eb)

**Comment by pikemurdy** [comment]
New URL (the site has launched) https://cci.utk.edu/home/about-us/

**Comment by pikemurdy** [comment]
Is this something we can investigate?

**Comment by reasterbrooknc** [comment]
@pikemurdy is there a new url with the text extending over the edge of the container? I'm not able to find/reproduce that. If you can, please add URL and browser info.

**Comment by pikemurdy** [comment]
Try here: https://cci.utk.edu/academics-and-programs/undergraduate-majors/

**Comment by pikemurdy** [comment]
I have edited this issue to be more current and specific.

**Comment by reasterbrooknc** [comment]
Ready for your review
- https://wds-dev.utk.edu/newcity-testing/kitchen-sink
- https://wds-dev.utk.edu/newcity-testing/core-blocks

I recommend reviewing all component pages, which can be accessed from the dev site navigation. 

QA list:
- Light gray contact cards need 16px font (not 18px)
