### ISSUE TITLE
Issue adding link beside right aligned image

### ISSUE THREAD

**Issue by pikemurdy** [utkwdn/utkwds#407]
**Describe the bug**

When adding a single link beside an image that is right aligned, the single link is pushed out of the usual paragraph text margin on the left-hand side (see screenshot). (This behavior does not happen when using columns, of course)

**Page URL**
https://brand.utk.edu/ocm-ls/testing-patterns/

**WDS Theme Version**
1.2

**To Reproduce**
Add an image. Add a paragraph beneath it. Align the image right so that the text flows around it from the left. Insert the single link pattern to the left of the image. Let the games begin!

**Expected behavior**
I would not expect the single link to break the left margin.

**Comment by reasterbrooknc** [comment]
Notes from Mike: Can fix by putting arrow on a link instead of paragraph class. CSS change.

**Comment by reasterbrooknc** [comment]
Test page for review @pikemurdy 
- https://wds-dev.utk.edu/newcity-testing/single-link-align-fix

**Comment by pikemurdy** [comment]
Looks good.
