### ISSUE TITLE
Add new fields to theme to allow 2 GTM containers

### ISSUE THREAD

**Issue by reasterbrooknc** [utkwdn/utkwds#408]
Adding this to customizer. 

@pikemurdy do we need to set the default container, or just allow 2 containers? If we need to set the default, please provide GTM ID.

Per 9/4 meeting, just allow 2 containers, no preset default.

**Comment by reasterbrooknc** [comment]
Ready for review @pikemurdy

**Comment by pikemurdy** [comment]
Looks right. I checked that the JS is added, I assume it 'works'. Didn't check with a real GTM code.
