### ISSUE TITLE
Contact card centered content

### ISSUE THREAD

**Issue by pikemurdy** [utkwdn/utkwds#426]
**Describe the bug**
Two-column contact cards, possibly due to the recent bug fix regarding length, are now vertically aligning text based on the center point of the longest item. See screenshot. Ideally, the text would all be vertically top-aligned.

**Page URL**
https://csw-dev.utk.edu/about/faculty-and-staff/

**WDS Theme Version**
1.2.1

**To Reproduce**

**Expected behavior**
That all text is vertically top aligned

**Screenshots**
![screenshot-verticalalign](https://github.com/user-attachments/assets/d7608071-218c-4485-a8d5-b639f8d415a5)

Not sure this was planned or not. But it seems like earlier the content was top aligned rather than centered, and centered kinda looks odd.

**Comment by nc-mhenderson** [comment]
Pattern settings need to be updated.

Copy styles will work at the root level component.

**Comment by reasterbrooknc** [comment]
Reassigning back to you @nc-mhenderson to look at the light grey and Smokey single cards.

**Comment by pikemurdy** [comment]
This looks good.
