### ISSUE TITLE
 Link group columns are breaking list item content between columns

### ISSUE THREAD

**Issue by pikemurdy** [utkwdn/utkwds#427]
**Describe the bug**
link group columns are breaking list item content between columns

**Page URL**
https://wds-dev.utk.edu/sp-component-test-03

**WDS Theme Version**
1.2.1

**To Reproduce**

**Expected behavior**
list content should stay grouped in same column. Seems to work correctly in Safari, Chrome, and Edge

**Screenshots**
![link-group-issue-firefox](https://github.com/user-attachments/assets/e3f921cf-3a0e-4bde-86dc-88a8168b02ed)

(The word humanities is on the top third column)

**Desktop (please complete the following information):**
 - Firefox
 (seems okay in chrome and safari)

**Comment by reasterbrooknc** [comment]
This is fixed and ready for your review @pikemurdy  https://wds-dev.utk.edu/sp-component-test-03

**Comment by pikemurdy** [comment]
This looks good.
