### ISSUE TITLE
In-page navigation issues

### ISSUE THREAD

**Issue by pikemurdy** [utkwdn/utkwds#442]
- [ ] No sticky position toggle for in-page navigation for editors. Can that setting be updated?

- [x] Mobile Sticky Navigation Adjustment:

> Kind of a bug, kind of a request. This is my fault for asking for the internal navigation to be sticky - and I still think that&#039;s super useful on desktop - but I&#039;ve since noticed that it being sticky on mobile is an issue as it takes up too much space to see the page.
> 
> I was originally modeling the idea off of enrollment management&#039;s admisssion pages with the sticky nav. I checked, and their internal nav doesn&#039;t show on mobile, only on desktop. So no clue how they did that but it does appear to be possible?
> 
> Please describe the purpose of this feature and why it is needed.
> 
> It&#039;s needed on desktop for long scrolls to make various parts of the page easily accessible to users w/o having to go all the way back to the top to access the internal navigation. It is not needed on mobile as it causes users to be unable to see the rest of the page.

**Comment by reasterbrooknc** [comment]
@pikemurdy the sticky toggle is available on the settings panel, which we are hiding from editors, as it allows them the option to make any pattern sticky. Other than the in-page navigation, our patterns are not designed or tested to be sticky. With that in mind, do you want us to open that option back up to editors for access to this setting, or are we okay limiting this ability to only admins?

**Comment by pikemurdy** [comment]
No, I think this can be set by admins.

**Comment by reasterbrooknc** [comment]
The sticky issue was addressed in 1.2.3. Closing this issue!
