### ISSUE TITLE
change heading blocks added on smokey version of billboard to white

### ISSUE THREAD

**Issue by nc-mhenderson** [utkwdn/utkwds#443]
The other versions all seem to grab the appropriate text color when I add a heading block in a billboard (e.g. an H3 on the paragraph side), but the smokey variant's text pulls in smokey-colored.

![issue screenshot](https://raw.githubusercontent.com/utkwdn/utkwds/frontback-assets/5b7c525a-b636-4d08-8577-34b6d10e3cc4.png)

URL: https://wds-dev.utk.edu/wp-admin/post.php?post=64170&action=edit

DOM: body>div#wpwrap>div#wpcontent>div#wpbody>div#wpbody-content>div:eq(1)>div#editor>div:eq(2)>div:eq(0)>div:eq(1)>div:eq(0)>div:eq(2)>div>div:eq(0)>div:eq(3)>div:eq(1)>div#block-a1218b53-9a0e-4a08-b175-1ed5b2ee464c>div#block-6b317d78-7650-4d75-be7a-41da58a99a33>div#block-be142462-4ee1-431b-84dd-7810ea7d6427>h3#block-e95b3c01-3e78-4297-92f0-f83de2bd6e2f

Useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:127.0) Gecko/20100101 Firefox/127.0

Platfom: MacIntel

Window size: 1472 x 772

Submitted by @wonkeythemonkey

Initially assigned to @nc-mhenderson

**Comment by reasterbrooknc** [comment]
QA on #300

**Comment by reasterbrooknc** [comment]
The heading color cannot be set unless the heading is inserted in the pattern. This component isn’t designed to have a heading in this area, so we're not able to set the heading color.
