### ISSUE TITLE
Add permission to the editor role.

### ISSUE THREAD

**Issue by pikemurdy** [utkwdn/utkwds#445]
Add permission to the editor role.

It's come up that we will need editors to be able to create/view/delete/edit Gravity Forms. Not sure if we can add permissions to the editor role or need to create a custom role.

**Comment by reasterbrooknc** [comment]
Are there additional permissions that need to be tweaked, or should we just add this for now? @pikemurdy

**Comment by reasterbrooknc** [comment]
> Are there additional permissions that need to be tweaked, or should we just add this for now? [@pikemurdy](https://github.com/pikemurdy)

Flagging this again to see if there are additional permissions we need to adjust?

**Comment by pikemurdy** [comment]
As far as I know, this role just needs Gravity Forms access for now.
